version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: morak
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: toor      # 루트 비밀번호만 설정
      MYSQL_DATABASE: morak          # 데이터베이스 이름 설정
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
