version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/your_database_name
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: your_password  # 환경 변수 확인 필요
    networks:
      - backend
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_ROOT_PASSWORD: your_password  # 환경 변수 확인 필요
    ports:
      - "3306:3306"
    networks:
      - backend
networks:
  backend:
    driver: bridge
