services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/morak
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor  # MySQL 패스워드 지정
    networks:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: morak
      MYSQL_ROOT_PASSWORD: toor  # MySQL root 비밀번호 설정
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
