services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_AI_OPENAI_API_KEY: "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"  # 실제 OpenAI API 키로 교체
    networks:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: morak
      MYSQL_ROOT_PASSWORD: toor  # MySQL root 비밀번호 설정
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
