services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: morak
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      OPENAI_API_KEY: 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

    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: morak
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
