services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: morak
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      OPENAI_API_KEY: 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
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/morak
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: morak
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
