version: '3.8'

services:
  app:
    build:
      context: .  # 현재 디렉터리를 Docker 빌드 컨텍스트로 설정
    ports:
      - "8080:8080"
  environment:
    SPRING_PROFILES_ACTIVE: prod
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/morak
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: toor

    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: morak
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
