spring:
  profiles:
    active: prod
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    openai:
      api-key: ${spring.ai.openai.api-key}
      model: gpt-3.5-turbo
      api:
        url: https://api.openai.com/v1/chat/completions
logging:
  level:
    root: info