spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://db:3306/morak  # db는 docker-compose.yml의 MySQL 서비스 이름
    username: root                   # root 사용자로 설정
    password: toor                   # MySQL 비밀번호를 직접 입력
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ai:
  openai:
    model: gpt-4o-mini
    api:
      url: https://api.openai.com/v1/chat/completions
