spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/morak
    username: root
    password: toor
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    openai:
      api-key: ${spring.ai.openai.api-key}
      model: gpt-4o-mini
      api:
        url: https://api.openai.com/v1/chat/completions