spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://db:3306/morak  # db는 docker-compose.yml에 정의된 MySQL 서비스의 이름
    username: root                   # root 사용자로 설정
    password: toor                   # 직접 입력한 비밀번호
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:
      api-key: ${spring.ai.openai.api-key}
      model: gpt-4o-mini
      api:
        url: https://api.openai.com/v1/chat/completions