spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://mysql:3306/morak
    username: root
    password: toor  # MySQL root 비밀번호와 동일하게 설정

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:
      api-key: ${spring.ai.openai.api-key}
      model: gpt-4o-mini
      api:
        url: https://api.openai.com/v1/chat/completions